apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-site
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hostname
        image: srgato/hostname-site:lastest 
        ports:
        - containerPort: 80
